import type { ExerciseSeed } from '../types';

/**
 * Segunda camada do banco: perguntas adicionais por unidade.
 * As variações mantêm o mesmo conceito em formatos diferentes para ampliar exposição
 * sem alterar a interface do jogo.
 */
const makeExtras = (prefix: string, facts: Array<[string,string,string,string]>, topicLabel: string): ExerciseSeed[] => {
  const out: ExerciseSeed[] = [];
  facts.forEach(([statement, explanation, wrong, correct]) => {
    const n = out.length / 3 + 1;
    out.push({ id: prefix + '-' + String(n).padStart(2,'0') + 'a', kind:'choice', difficulty:2, prompt:'Qual afirmação está correta?', options:[correct, wrong, 'As duas estão sempre erradas', 'Não é possível concluir'], answer:0, explanation });
    out.push({ id: prefix + '-' + String(n).padStart(2,'0') + 'b', kind:'boolean', difficulty:1, prompt:'Verdadeiro ou falso?', statement, answer:true, explanation });
    out.push({ id: prefix + '-' + String(n).padStart(2,'0') + 'c', kind:'blank', difficulty:3, prompt:'Complete a ideia clínica', sentence: statement.replace(/\.$/, '') + '. O ponto-chave é ___', answer:correct, bank:[correct, wrong, 'tempo', 'contexto'], explanation });
  });
  return out;
};

export const EXPANDED_EXERCISES: Record<string, ExerciseSeed[]> = {
  'exame-clinico': makeExtras('exclx', [["A anamnese deve anteceder o exame físico detalhado.","Anamnese e história médica orientam o exame e ajudam a identificar riscos.","começar pelo exame sem conhecer a história clínica","revisar a história antes de interpretar os achados"],["A queixa principal deve ser registrada com as palavras do paciente sempre que possível.","A queixa principal registra o motivo que levou o paciente à consulta.","trocar a queixa por um diagnóstico","ignorar duração e evolução"],["Percussão avalia principalmente a resposta do periodonto apical e lateral.","Dor à percussão pode indicar inflamação do ligamento periodontal.","vitalidade pulpar diretamente","cor da mucosa"],["Palpação ajuda a avaliar dor, expansão e consistência dos tecidos.","A palpação complementa inspeção e outros testes clínicos.","substituir todos os exames complementares","medir a cor do esmalte"],["O exame intraoral deve seguir uma sequência sistemática.","Uma sequência fixa reduz a chance de esquecer regiões ou estruturas.","examinar apenas o dente que dói","evitar registrar achados negativos relevantes"],["Diagnóstico deve integrar história, exame e exames complementares.","Nenhum exame isolado deve ser interpretado fora do contexto clínico.","basear o diagnóstico em uma imagem isolada","ignorar sintomas do paciente"]], 'exame-clinico'),
  'radiologia': makeExtras('radx', [["Bite-wing é especialmente útil para avaliar cáries proximais posteriores.","A técnica mostra coroas posteriores e crista alveolar com pouca sobreposição proximal.","diagnosticar fratura mandibular","avaliar apenas ápices"],["Uma radiolucidez aparece mais escura na imagem.","Estruturas que atenuam menos o feixe deixam áreas mais escuras.","radiopacidade","esclerose"],["Sobreposição proximal costuma exigir correção da angulação horizontal.","A angulação horizontal adequada separa os contatos proximais.","aumento do tempo de exposição","mudança do contraste no monitor"],["A radiografia periapical deve incluir a região apical de interesse.","Cortar o ápice pode comprometer a pergunta clínica em endodontia.","somente a coroa","somente a crista alveolar"],["ALARA orienta manter a exposição tão baixa quanto razoavelmente possível.","Justificação, colimação e técnica correta ajudam a reduzir exposição desnecessária.","aumentar a dose em toda repetição","usar radiografia sem indicação"],["Radiografia não substitui teste de sensibilidade pulpar.","A imagem mostra anatomia e alterações estruturais, não a resposta sensorial da polpa.","diagnóstico clínico completo","anamnese"]], 'radiologia'),
  'anestesia': makeExtras('anx', [["Aspiração antes da deposição ajuda a reduzir o risco de injeção intravascular.","A aspiração é parte importante da técnica segura.","dispensar a anamnese","aumentar a velocidade de injeção"],["Lidocaína a 2% corresponde a 20 mg/ml.","A concentração percentual permite converter o volume em miligramas.","2 mg/ml","200 mg/ml"],["Um tubete de 1,8 ml de lidocaína a 2% contém 36 mg.","O cálculo é 20 mg/ml multiplicado por 1,8 ml.","18 mg","72 mg"],["Tecido inflamado pode dificultar a anestesia local.","O pH mais baixo altera a proporção de moléculas capazes de atravessar a membrana.","inflamação sempre aumenta a eficácia","inflamação não interfere"],["A injeção lenta tende a reduzir desconforto e reação sistêmica.","Velocidade controlada melhora a tolerância do paciente.","injetar o mais rápido possível","evitar aspiração"],["Dose máxima deve ser calculada pelo anestésico, concentração e peso do paciente.","O limite não deve ser estimado apenas pelo número de tubetes.","usar sempre a mesma dose para todos","ignorar o peso"]], 'anestesia'),
  'isolamento': makeExtras('isox', [["Isolamento absoluto melhora controle de umidade e acesso ao campo.","O dique reduz contaminação por saliva e protege o paciente.","aumentar a umidade","substituir anestesia"],["O grampo deve ficar estável antes da colocação definitiva do lençol.","Estabilidade evita deslocamentos durante o procedimento.","ser colocado frouxo","ser apoiado apenas no lençol"],["O lençol deve permitir vedação adequada ao redor do dente.","A vedação ajuda a manter o campo seco.","deixar saliva entrar","cobrir apenas metade da coroa"],["Contato proximal pode dificultar passagem do fio antes do isolamento.","Checar o contato ajuda a evitar rasgos e deslocamento do lençol.","ignorar o ponto de contato","cortar o grampo"],["Vazamento de saliva compromete procedimentos adesivos.","Controle de umidade é crítico para adesão previsível.","melhorar a adesão","não ter qualquer efeito"],["O isolamento também reduz risco de aspiração ou deglutição de pequenos instrumentos.","O campo isolado cria uma barreira adicional de segurança.","aumentar o risco de aspiração","eliminar a necessidade de sucção"]], 'isolamento'),
  'preventiva': makeExtras('prevx', [["Frequência de ingestão de açúcar é um importante determinante do risco de cárie.","Exposições repetidas mantêm episódios de queda de pH mais frequentes.","somente a marca do alimento","apenas a temperatura"],["Dentifrício fluoretado é uma medida importante de prevenção de cárie.","A exposição frequente ao flúor favorece controle da doença.","fator de risco obrigatório","substituto de higiene"],["Lesão de cárie não cavitada pode ser manejada de forma não invasiva.","Controle de biofilme, flúor e dieta podem favorecer a estabilização.","restauração obrigatória","exodontia imediata"],["Selantes são usados principalmente para proteger fóssulas e fissuras de risco.","A indicação depende do risco e da anatomia, além do controle de umidade.","qualquer superfície lisa","somente dentes anteriores"],["Xerostomia aumenta risco de cárie.","Menor fluxo salivar reduz mecanismos protetores da saliva.","proteção completa contra cárie","fator irrelevante"],["Prevenção eficaz inclui mudança de comportamento individualizada.","Uma orientação prática e possível tende a ser mais útil do que instruções genéricas.","apenas profilaxia mecânica","prometer ausência de novas lesões"]], 'preventiva'),
  'periodontia': makeExtras('periox', [["Sangramento à sondagem é um indicador clínico de inflamação gengival.","O achado deve ser interpretado junto aos demais sinais periodontais.","sinal exclusivo de cárie","medida direta de vitalidade pulpar"],["Profundidade de sondagem é medida da margem gengival até o fundo do sulco ou bolsa.","A medida depende da posição da margem e da inserção.","da cúspide ao ápice","do contato proximal ao fundo"],["Nível clínico de inserção considera a posição da margem gengival.","Ele ajuda a avaliar perda de inserção ao longo do tempo.","somente a cor da gengiva","apenas mobilidade"],["Biofilme é um fator etiológico central na doença periodontal inflamatória.","Controle de biofilme é parte essencial do tratamento periodontal.","causa exclusiva de toda doença sistêmica","fator sem importância"],["Manutenção periodontal é necessária após tratamento ativo.","O risco pode persistir e precisa de acompanhamento individualizado.","desnecessária após raspagem","substituível por uma única profilaxia"],["Furca deve ser avaliada em dentes multirradiculares.","Envolvimento de furca altera prognóstico e planejamento.","somente em incisivos","apenas em dentes decíduos"]], 'periodontia'),
  'dentistica': makeExtras('dentx', [["A seleção de cor deve ocorrer antes do isolamento e com o dente hidratado.","A desidratação pode alterar a percepção da cor.","depois de desidratar o dente","somente após polimento"],["Controle de umidade é essencial para protocolos adesivos.","Saliva e sangue podem comprometer a interface adesiva.","irrelevante para adesão","melhor quando há contaminação"],["Matriz seccional ajuda a reconstruir contato proximal em restaurações classe II.","O sistema combina matriz, cunha e anel separador em muitos casos.","serve apenas para clareamento","substitui o adesivo"],["Excesso proximal de resina pode dificultar higiene.","Contornos inadequados favorecem retenção de biofilme.","melhorar a higiene","não interferir no periodonto"],["Fotoativação adequada é necessária para polimerização previsível.","Tempo, intensidade, distância e acesso influenciam o resultado.","ser opcional","ser desnecessária em resina composta"],["Ajuste oclusal deve ser conferido antes da liberação.","Contato prematuro pode gerar dor à mastigação.","ignorado em restaurações posteriores","substituído por radiografia"]], 'dentistica'),
  'endodontia': makeExtras('endx', [["Hipoclorito de sódio tem ação antimicrobiana e capacidade de dissolver tecido orgânico.","É um dos principais irrigantes da endodontia.","serve apenas para lubrificar","não interage com tecido orgânico"],["EDTA auxilia na remoção da porção inorgânica da smear layer.","O quelante complementa a ação dos irrigantes durante o preparo.","substitui anestesia","remove apenas esmalte"],["Isolamento absoluto é obrigatório no tratamento endodôntico.","Ele reduz contaminação e protege o paciente contra irrigantes e instrumentos.","dispensável em qualquer caso","usado apenas para estética"],["Comprimento de trabalho define o limite apical do preparo.","A determinação combina métodos clínicos e radiográficos conforme o protocolo.","é irrelevante para instrumentação","é igual ao comprimento da coroa"],["Dor espontânea prolongada pode indicar pulpite irreversível.","O diagnóstico deve ser confirmado com testes e história clínica.","diagnóstico exclusivo de necrose","sinal específico de gengivite"],["Antibiótico não substitui drenagem e desinfecção em infecção endodôntica localizada.","A indicação sistêmica depende de sinais de disseminação ou comprometimento sistêmico.","sempre obrigatório","substituto do tratamento local"]], 'endodontia'),
  'cirurgia': makeExtras('cirx', [["Radiografia pré-operatória deve ser interpretada em relação às estruturas anatômicas de risco.","Canal mandibular e seio maxilar podem alterar o planejamento.","somente a cor do dente","apenas a restauração"],["Sindesmotomia ajuda a liberar fibras gengivais antes da luxação.","Isso reduz laceração e facilita a movimentação controlada.","substitui anestesia","é feita depois da sutura"],["Hemostasia local inclui compressão e, quando indicado, sutura ou hemostático.","Controle local é a primeira linha em muitos sangramentos pós-operatórios.","ignorar o sangramento","liberar o paciente imediatamente"],["Alveolite costuma apresentar dor intensa alguns dias após a extração e perda do coágulo.","O quadro é diferente da dor esperada imediatamente após a cirurgia.","sempre ocorre no primeiro minuto","é causada apenas por alergia"],["Parestesia do lábio inferior é risco relevante em terceiros molares inferiores próximos ao canal mandibular.","A proximidade anatômica deve entrar no planejamento e consentimento.","risco impossível","exclusivo de molares superiores"],["Anticoagulante não deve ser suspenso por conta própria para uma exodontia.","O manejo depende do medicamento, risco trombótico e planejamento hemostático.","sempre suspender por três dias","nunca considerar medicação"]], 'cirurgia'),
  'protese': makeExtras('protx', [["Uma moldagem com o término cervical incompleto deve ser repetida.","A margem precisa estar reproduzida para permitir adaptação adequada.","aceita em qualquer caso","corrigida apenas no laboratório"],["O provisório protege o preparo e ajuda a manter posição e função.","Também permite testar forma, contatos e estética.","serve somente para estética","não tem função clínica"],["Afastamento gengival ajuda a expor o término subgengival.","Controle de fluido e visualização são essenciais para moldagem.","substitui o preparo","elimina a necessidade de higiene"],["Contato proximal deve ser conferido antes da cimentação definitiva.","Contato excessivo impede assentamento e aberto favorece impactação alimentar.","dispensável","avaliado apenas depois de cimentar"],["Saúde periodontal deve estar controlada antes da prótese definitiva.","Inflamação e sangramento dificultam moldagem e estabilidade tecidual.","irrelevante para a margem","corrigida somente no laboratório"],["Excesso de cimento subgengival pode provocar inflamação periodontal.","A remoção completa dos excessos faz parte da instalação.","melhora a saúde gengival","não tem relação com periodonto"]], 'protese'),
  'odontopediatria': makeExtras('pedx', [["Manejo comportamental deve considerar idade, desenvolvimento e experiência prévia.","A comunicação precisa ser adaptada à criança.","igual para todos","baseado apenas no tamanho da criança"],["Dentição decídua tem características anatômicas próprias.","Câmaras pulpares e espessura de tecidos diferem dos permanentes.","idêntica à permanente","sem diferença clínica"],["Fluoretação deve considerar risco de cárie e idade.","Dose e frequência dependem da orientação profissional e exposição total ao flúor.","independente da idade","sempre contraindicada"],["Trauma em dente decíduo exige avaliar também o germe do permanente.","A proximidade anatômica torna esse cuidado importante.","apenas a estética","somente o lábio"],["Selante pode ser indicado em molares permanentes de crianças com risco de cárie.","A anatomia retentiva e o risco individual orientam a decisão.","obrigatório em toda criança","exclusivo de dentes anteriores"],["Consentimento e comunicação com responsáveis fazem parte do atendimento infantil.","O plano deve ser explicado de forma compreensível e respeitosa.","dispensáveis","substituídos por silêncio clínico"]], 'odontopediatria'),
};
