import type { ExerciseSeed } from '../types';

export const IMPL_EXERCISES: ExerciseSeed[] = [
  {
    id: 'impl-01',
    kind: 'multi',
    difficulty: 3,
    prompt: 'Quais princípios se aplicam ao planejamento por imagem de implantes?',
    options: [
      'A posição proposta deve ser relacionada ao volume ósseo e às estruturas anatômicas.',
      'A aquisição tridimensional deve ser clinicamente justificada e otimizada quanto a campo e exposição.',
      'A imagem elimina a necessidade de exame clínico e planejamento protético.',
      'O planejamento deve partir do resultado protético pretendido.',
    ],
    answers: [0, 1, 3],
    explanation: 'Imagem, exame clínico e planejamento reverso são complementares. A radiação deve ser justificada e limitada ao necessário para responder à questão clínica.',
  },
  {
    id: 'impl-02',
    kind: 'choice',
    difficulty: 2,
    prompt: 'Qual alternativa define corretamente osseointegração?',
    options: [
      'Conexão estrutural e funcional direta entre osso vivo e a superfície do implante.',
      'Fixação instantânea produzida apenas pelo torque de inserção.',
      'Formação de uma cápsula fibrosa espessa ao redor do implante.',
      'União que independe da vascularização e das condições do leito ósseo.',
    ],
    answer: 0,
    explanation: 'Estabilidade inicial suficiente, biocompatibilidade, técnica, controle de micromovimento e condições locais e sistêmicas influenciam a formação e manutenção dessa interface.',
  },
  {
    id: 'impl-03',
    kind: 'boolean',
    difficulty: 1,
    prompt: 'Avalie a manutenção peri-implantar.',
    statement: 'Após a osseointegração, o implante torna-se imune à inflamação induzida por biofilme.',
    answer: false,
    explanation: 'Mucosite e peri-implantite podem ocorrer. Higiene, controle de fatores de risco e manutenção profissional individualizada integram o tratamento.',
  },
  {
    id: 'impl-04',
    kind: 'choice',
    difficulty: 3,
    prompt: 'No planejamento de um implante na mandíbula posterior, qual avaliação anatômica é essencial?',
    options: [
      'Localizar o canal mandibular e considerar variações, limites da imagem e margem de segurança apropriada.',
      'Presumir que o nervo alveolar inferior está sempre no centro do rebordo.',
      'Procurar o nervo alveolar inferior no interior do seio maxilar.',
      'Ignorar a imagem se houver altura óssea aparente ao exame visual.',
    ],
    answer: 0,
    explanation: 'A posição do canal e variações como bifurcações ou extensão anterior influenciam o comprimento, a posição e a segurança do procedimento.',
  },
  {
    id: 'impl-05',
    kind: 'boolean',
    difficulty: 2,
    prompt: 'Avalie a anatomia da maxila posterior.',
    statement: 'A pneumatização e a anatomia do seio maxilar podem limitar a altura óssea disponível para implantes posteriores.',
    answer: true,
    explanation: 'Altura e largura do rebordo, anatomia sinusal, saúde do seio e necessidade de aumento devem ser avaliadas individualmente.',
  },
  {
    id: 'impl-06',
    kind: 'multi',
    difficulty: 2,
    prompt: 'Quais elementos pertencem ao planejamento reverso em implantodontia?',
    options: [
      'Posição e contorno da futura prótese.',
      'Exigências funcionais, fonéticas e estéticas.',
      'Acesso para higiene e possibilidade de manutenção.',
      'Escolha da posição cirúrgica sem considerar a reabilitação.',
    ],
    answers: [0, 1, 2],
    explanation: 'O posicionamento tridimensional do implante deve viabilizar uma prótese funcional, higienizável e biologicamente compatível, respeitando a anatomia.',
  },
  {
    id: 'impl-07',
    kind: 'blank',
    difficulty: 2,
    prompt: 'Complete a frase',
    sentence: 'A estabilidade obtida pelo travamento mecânico do implante no momento da instalação é chamada de estabilidade ___.',
    answer: 'primária',
    bank: ['primária', 'secundária', 'terciária', 'protética'],
    explanation: 'A estabilidade primária resulta da interação mecânica com o leito ósseo. A estabilidade secundária surge depois, com a formação e remodelação óssea na interface.',
  },
  {
    id: 'impl-08',
    kind: 'order',
    difficulty: 2,
    prompt: 'Ordene as etapas gerais de uma reabilitação implantossuportada convencional',
    steps: [
      'Realizar diagnóstico e planejamento reverso clínico e por imagem',
      'Instalar o implante na posição tridimensional planejada',
      'Acompanhar a cicatrização e a osseointegração',
      'Registrar a posição do implante por moldagem ou escaneamento',
      'Provar e instalar a prótese com ajuste dos contatos',
      'Orientar higiene e iniciar manutenção peri-implantar periódica',
    ],
    explanation: 'No fluxo convencional, a fase protética definitiva ocorre após cicatrização apropriada. Protocolos imediatos existem, mas exigem indicação, estabilidade e controle de carga específicos.',
  },
  {
    id: 'impl-09',
    kind: 'match',
    difficulty: 3,
    prompt: 'Relacione o conceito peri-implantar com sua definição',
    pairs: [
      { left: 'Estabilidade primária', right: 'Travamento mecânico presente na instalação' },
      { left: 'Osseointegração', right: 'Contato estrutural e funcional direto entre osso vivo e implante' },
      { left: 'Mucosite peri-implantar', right: 'Inflamação reversível da mucosa sem perda óssea progressiva' },
      { left: 'Peri-implantite', right: 'Inflamação associada à perda progressiva do osso de suporte' },
    ],
    explanation: 'Sangramento e inflamação sem perda óssea progressiva caracterizam mucosite; a peri-implantite inclui perda óssea além da remodelação inicial. Diagnóstico requer comparação clínica e radiográfica.',
  },
];
