import type { ExerciseSeed } from '../types';

export const MAT_EXERCISES: ExerciseSeed[] = [
  {
    id: 'mat-01',
    kind: 'boolean',
    difficulty: 1,
    prompt: 'Avalie uma propriedade do cimento de ionômero de vidro.',
    statement: 'O ionômero de vidro pode aderir quimicamente ao tecido dental e liberar flúor, com comportamento dependente da formulação.',
    answer: true,
    explanation: 'A reação ácido-base permite interação com o tecido dental. Propriedades mecânicas e liberação de flúor variam entre categorias e produtos.',
  },
  {
    id: 'mat-02',
    kind: 'multi',
    difficulty: 3,
    prompt: 'Quais fatores influenciam a fotoativação de uma resina composta fotopolimerizável?',
    options: [
      'Irradiância e tempo de exposição.',
      'Compatibilidade entre o espectro da luz e o fotoiniciador.',
      'Distância da fonte, espessura do incremento, cor e translucidez.',
      'Somente a temperatura da água usada no enxágue.',
    ],
    answers: [0, 1, 2],
    explanation: 'A exposição radiante e a chegada de luz em espectro adequado ao material influenciam a conversão; técnica e geometria clínica também importam.',
  },
  {
    id: 'mat-03',
    kind: 'choice',
    difficulty: 2,
    prompt: 'Qual afirmação descreve corretamente o silicone de adição?',
    options: [
      'É um elastômero de moldagem de alta precisão, cujo desempenho depende de manipulação e controle do campo.',
      'É um cimento metálico usado apenas em restaurações diretas.',
      'Não registra detalhes e é indicado somente para modelos preliminares.',
      'Após a presa, retorna ao estado fluido com aquecimento clínico.',
    ],
    answer: 0,
    explanation: 'Silicones de adição apresentam boa reprodução e estabilidade dimensional, mas umidade, deslocamento tecidual, proporção e técnica afetam o resultado.',
  },
  {
    id: 'mat-04',
    kind: 'boolean',
    difficulty: 2,
    prompt: 'Avalie o comportamento do alginato.',
    statement: 'O alginato é um hidrocoloide reversível e pode voltar ao estado fluido após a presa.',
    answer: false,
    explanation: 'O alginato é irreversível e tem estabilidade dimensional limitada. Deve ser desinfetado e vazado no intervalo recomendado para reduzir sinérese e embebição.',
  },
  {
    id: 'mat-05',
    kind: 'choice',
    difficulty: 3,
    prompt: 'O que determina a seleção de um cimento resinoso para uma restauração indireta?',
    options: [
      'Substrato dental, material e espessura da restauração, retenção e compatibilidade do protocolo adesivo e de polimerização.',
      'Apenas a cor da embalagem do cimento.',
      'Uma indicação universal, igual para toda restauração indireta.',
      'Somente a preferência do laboratório, sem considerar o dente.',
    ],
    answer: 0,
    explanation: 'Cerâmicas vítreas, óxidos cerâmicos, compósitos e diferentes substratos exigem tratamentos e mecanismos de cura compatíveis.',
  },
  {
    id: 'mat-06',
    kind: 'multi',
    difficulty: 2,
    prompt: 'Quais propriedades podem alterar a indicação clínica de um material odontológico?',
    options: [
      'Resistência e tenacidade à fratura.',
      'Módulo de elasticidade.',
      'Desgaste e estabilidade química.',
      'Somente o nome comercial.',
    ],
    answers: [0, 1, 2],
    explanation: 'Materiais respondem de modo distinto a carga, deformação, fadiga, desgaste e ambiente oral; a seleção deve relacionar propriedades à situação clínica.',
  },
  {
    id: 'mat-07',
    kind: 'blank',
    difficulty: 3,
    prompt: 'Complete a frase',
    sentence: 'Em cerâmicas vítreas condicionáveis, o agente que favorece a união química entre a fase inorgânica e a resina é o ___.',
    answer: 'silano',
    bank: ['silano', 'alginato', 'eugenol', 'sulfato de cálcio'],
    explanation: 'Após o tratamento de superfície indicado para a cerâmica, o silano atua como agente de união entre a sílica e a matriz resinosa. O protocolo deve seguir o material e o fabricante.',
  },
  {
    id: 'mat-08',
    kind: 'order',
    difficulty: 2,
    prompt: 'Ordene a manipulação clínica de uma moldagem com alginato',
    steps: [
      'Selecionar e provar uma moldeira de tamanho adequado',
      'Dosar água e pó conforme as instruções do fabricante',
      'Espatular pelo tempo recomendado até obter mistura homogênea',
      'Carregar a moldeira, inserir e manter imóvel até a presa',
      'Remover com movimento firme, enxaguar, inspecionar e desinfetar',
      'Vazar o molde no intervalo recomendado para o produto',
    ],
    explanation: 'Proporção e tempo de mistura afetam a presa e a resistência. Como o alginato sofre alterações dimensionais, desinfecção e vazamento devem respeitar o protocolo do produto.',
  },
  {
    id: 'mat-09',
    kind: 'match',
    difficulty: 2,
    prompt: 'Relacione o material de moldagem com uma característica',
    pairs: [
      { left: 'Alginato', right: 'Hidrocoloide irreversível com estabilidade dimensional limitada' },
      { left: 'Silicone de adição', right: 'Elastômero com alta precisão e boa estabilidade dimensional' },
      { left: 'Poliéter', right: 'Elastômero relativamente rígido após a presa' },
      { left: 'Godiva', right: 'Material termoplástico que amolece com aquecimento' },
    ],
    explanation: 'A seleção considera precisão, elasticidade, rigidez, umidade, extensão da moldagem e tempo até o vazamento. Nenhum material compensa uma técnica ou indicação inadequada.',
  },
];
