import type { ExerciseSeed } from '../types';

export const GERI_EXERCISES: ExerciseSeed[] = [
  {
    id: 'geri-01',
    kind: 'multi',
    difficulty: 2,
    prompt: 'Por que a lista completa de medicamentos deve ser revisada na consulta do paciente idoso?',
    options: [
      'Para identificar interações com medicamentos odontológicos.',
      'Para reconhecer efeitos orais, risco de sangramento e sedação.',
      'Para coordenar possíveis alterações com o prescritor, sem suspender tratamentos automaticamente.',
      'Porque a polifarmácia elimina a necessidade de anamnese clínica.',
    ],
    answers: [0, 1, 2],
    explanation: 'Medicamentos prescritos, isentos de receita e fitoterápicos podem modificar a saúde oral e a segurança do atendimento.',
  },
  {
    id: 'geri-02',
    kind: 'choice',
    difficulty: 2,
    prompt: 'Qual alternativa diferencia corretamente xerostomia e hipossalivação?',
    options: [
      'Xerostomia é sensação subjetiva de boca seca; hipossalivação é redução objetiva do fluxo salivar, e uma pode ocorrer sem a outra.',
      'São sinônimos obrigatórios e só podem ser diagnosticados por radiografia.',
      'Xerostomia é aumento de saliva causado exclusivamente pelo envelhecimento.',
      'Hipossalivação não influencia cárie, mucosa ou retenção de próteses.',
    ],
    answer: 0,
    explanation: 'Medicamentos são causa frequente. A hipossalivação aumenta risco de cárie, inclusive radicular, enquanto xerostomia afeta conforto e função.',
  },
  {
    id: 'geri-03',
    kind: 'boolean',
    difficulty: 1,
    prompt: 'Avalie o risco de cárie radicular.',
    statement: 'Exposição radicular, biofilme, dieta cariogênica e redução salivar podem aumentar o risco de cárie de raiz.',
    answer: true,
    explanation: 'A prevenção deve ser individualizada e pode incluir higiene assistida, controle dietético, fluoretos e acompanhamento segundo o risco.',
  },
  {
    id: 'geri-04',
    kind: 'multi',
    difficulty: 2,
    prompt: 'Quais fatores devem orientar a adaptação das instruções de higiene oral?',
    options: [
      'Destreza manual, visão e capacidade de compreender e executar a técnica.',
      'Grau de dependência e disponibilidade de apoio.',
      'Preferências, rotina e recursos do paciente.',
      'A exigência de usar a mesma técnica para todas as pessoas.',
    ],
    answers: [0, 1, 2],
    explanation: 'Escovas adaptadas ou elétricas, recursos interproximais e apoio de cuidador podem ser necessários, preservando a participação do paciente.',
  },
  {
    id: 'geri-05',
    kind: 'choice',
    difficulty: 2,
    prompt: 'Qual orientação é mais adequada para uma prótese removível?',
    options: [
      'Higienizar prótese e tecidos orais diariamente, removê-la durante o sono em regra e realizar acompanhamento periódico.',
      'Mantê-la continuamente na boca para impedir qualquer alteração do rebordo.',
      'Usar dentifrício muito abrasivo para remover desgaste e riscos.',
      'Procurar avaliação apenas quando a prótese quebrar.',
    ],
    answer: 0,
    explanation: 'Uso contínuo e biofilme favorecem estomatite protética e trauma. Armazenamento e produtos de limpeza devem seguir o material e a orientação profissional.',
  },
  {
    id: 'geri-06',
    kind: 'boolean',
    difficulty: 3,
    prompt: 'Avalie o cuidado de uma pessoa com alteração cognitiva.',
    statement: 'A presença de alteração cognitiva impede qualquer tratamento odontológico e transfere automaticamente todas as decisões ao cuidador.',
    answer: false,
    explanation: 'É necessário avaliar capacidade decisória, adaptar a comunicação e usar decisão apoiada quando indicada, preservando autonomia, preferências, consentimento e segurança.',
  },
  {
    id: 'geri-07',
    kind: 'blank',
    difficulty: 2,
    prompt: 'Complete a frase',
    sentence: 'Em pessoas idosas, maior carga farmacológica ___ pode contribuir para redução salivar e sensação de boca seca.',
    answer: 'anticolinérgica',
    bank: ['anticolinérgica', 'antiagregante', 'anticoagulante', 'hipoglicemiante'],
    explanation: 'Medicamentos com efeitos anticolinérgicos podem reduzir a secreção salivar. A revisão deve considerar o efeito cumulativo, sem suspender ou alterar tratamentos sem coordenação com o prescritor.',
  },
  {
    id: 'geri-08',
    kind: 'order',
    difficulty: 1,
    prompt: 'Ordene a higiene noturna de uma prótese total removível',
    steps: [
      'Remover a prótese sobre uma pia protegida ou recipiente com água',
      'Enxaguar para retirar resíduos soltos',
      'Escovar todas as superfícies com escova e produto não abrasivo apropriados',
      'Deixar a prótese fora da boca durante o sono e armazená-la conforme o material',
      'Enxaguar antes de recolocá-la pela manhã',
    ],
    explanation: 'A remoção noturna reduz o contato contínuo da mucosa com a prótese. Produtos e armazenamento devem ser compatíveis com o material, e os tecidos orais também precisam de higiene diária.',
  },
  {
    id: 'geri-09',
    kind: 'match',
    difficulty: 2,
    prompt: 'Relacione o achado geriátrico com uma implicação para o cuidado odontológico',
    pairs: [
      { left: 'Hipossalivação', right: 'Maior risco de cárie radicular e dificuldade com próteses' },
      { left: 'Disfagia', right: 'Necessidade de reduzir risco de aspiração durante o atendimento' },
      { left: 'Comprometimento cognitivo', right: 'Comunicação adaptada e avaliação da capacidade decisória' },
      { left: 'Destreza manual reduzida', right: 'Indicação de dispositivos de higiene adaptados ou apoio do cuidador' },
    ],
    explanation: 'O plano deve integrar função, cognição, autonomia, comorbidades e suporte disponível. Idade cronológica isolada não define capacidade nem contraindica tratamento.',
  },
];
