import type { ExerciseSeed } from '../types';

export const GERI_EXERCISES: ExerciseSeed[] = [
  {
    id: 'geri-01',
    kind: 'multi',
    difficulty: 2,
    prompt: 'Por que a lista completa de medicamentos deve ser revisada na consulta do paciente idoso?',
    options: [
      'Para identificar interações com medicamentos odontológicos.',
      'Para reconhecer efeitos orais, risco de sangramento e sedação.',
      'Para coordenar possíveis alterações com o prescritor, sem suspender tratamentos automaticamente.',
      'Porque a polifarmácia elimina a necessidade de anamnese clínica.',
    ],
    answers: [0, 1, 2],
    explanation: 'Medicamentos prescritos, isentos de receita e fitoterápicos podem modificar a saúde oral e a segurança do atendimento.',
  },
  {
    id: 'geri-02',
    kind: 'choice',
    difficulty: 2,
    prompt: 'Qual alternativa diferencia corretamente xerostomia e hipossalivação?',
    options: [
      'Xerostomia é sensação subjetiva de boca seca; hipossalivação é redução objetiva do fluxo salivar, e uma pode ocorrer sem a outra.',
      'São sinônimos obrigatórios e só podem ser diagnosticados por radiografia.',
      'Xerostomia é aumento de saliva causado exclusivamente pelo envelhecimento.',
      'Hipossalivação não influencia cárie, mucosa ou retenção de próteses.',
    ],
    answer: 0,
    explanation: 'Medicamentos são causa frequente. A hipossalivação aumenta risco de cárie, inclusive radicular, enquanto xerostomia afeta conforto e função.',
  },
  {
    id: 'geri-03',
    kind: 'boolean',
    difficulty: 1,
    prompt: 'Avalie o risco de cárie radicular.',
    statement: 'Exposição radicular, biofilme, dieta cariogênica e redução salivar podem aumentar o risco de cárie de raiz.',
    answer: true,
    explanation: 'A prevenção deve ser individualizada e pode incluir higiene assistida, controle dietético, fluoretos e acompanhamento segundo o risco.',
  },
  {
    id: 'geri-04',
    kind: 'multi',
    difficulty: 2,
    prompt: 'Quais fatores devem orientar a adaptação das instruções de higiene oral?',
    options: [
      'Destreza manual, visão e capacidade de compreender e executar a técnica.',
      'Grau de dependência e disponibilidade de apoio.',
      'Preferências, rotina e recursos do paciente.',
      'A exigência de usar a mesma técnica para todas as pessoas.',
    ],
    answers: [0, 1, 2],
    explanation: 'Escovas adaptadas ou elétricas, recursos interproximais e apoio de cuidador podem ser necessários, preservando a participação do paciente.',
  },
  {
    id: 'geri-05',
    kind: 'choice',
    difficulty: 2,
    prompt: 'Qual orientação é mais adequada para uma prótese removível?',
    options: [
      'Higienizar prótese e tecidos orais diariamente, removê-la durante o sono em regra e realizar acompanhamento periódico.',
      'Mantê-la continuamente na boca para impedir qualquer alteração do rebordo.',
      'Usar dentifrício muito abrasivo para remover desgaste e riscos.',
      'Procurar avaliação apenas quando a prótese quebrar.',
    ],
    answer: 0,
    explanation: 'Uso contínuo e biofilme favorecem estomatite protética e trauma. Armazenamento e produtos de limpeza devem seguir o material e a orientação profissional.',
  },
  {
    id: 'geri-06',
    kind: 'boolean',
    difficulty: 3,
    prompt: 'Avalie o cuidado de uma pessoa com alteração cognitiva.',
    statement: 'A presença de alteração cognitiva impede qualquer tratamento odontológico e transfere automaticamente todas as decisões ao cuidador.',
    answer: false,
    explanation: 'É necessário avaliar capacidade decisória, adaptar a comunicação e usar decisão apoiada quando indicada, preservando autonomia, preferências, consentimento e segurança.',
  },
];
