import type { ExerciseSeed } from '../types';

export const ORTO_EXERCISES: ExerciseSeed[] = [
  {
    id: 'orto-01',
    kind: 'multi',
    difficulty: 2,
    prompt: 'Quais tecidos participam diretamente da resposta ao movimento ortodôntico?',
    options: [
      'Ligamento periodontal.',
      'Osso alveolar.',
      'Tecidos vasculares e celulares associados à remodelação.',
      'Somente o esmalte, por desgaste da face proximal.',
    ],
    answers: [0, 1, 2],
    explanation: 'Forças controladas alteram o ambiente do ligamento periodontal e desencadeiam remodelação óssea; o movimento não ocorre por desgaste dentário.',
  },
  {
    id: 'orto-02',
    kind: 'choice',
    difficulty: 1,
    prompt: 'O que o overjet descreve?',
    options: [
      'A relação horizontal entre os incisivos superiores e inferiores.',
      'A sobreposição vertical dos incisivos.',
      'O desvio da linha média posterior.',
      'A distância entre os primeiros molares no sentido transversal.',
    ],
    answer: 0,
    explanation: 'Overjet é a relação horizontal anterior e pode ser positivo, reduzido ou reverso; overbite descreve a dimensão vertical.',
  },
  {
    id: 'orto-03',
    kind: 'boolean',
    difficulty: 1,
    prompt: 'Avalie a definição de overbite.',
    statement: 'Overbite é uma medida exclusivamente horizontal e sinônimo de overjet.',
    answer: false,
    explanation: 'Overbite descreve a sobreposição vertical dos incisivos e deve ser avaliado separadamente do overjet.',
  },
  {
    id: 'orto-04',
    kind: 'choice',
    difficulty: 2,
    prompt: 'Por que a contenção é indicada após a fase ativa do tratamento ortodôntico?',
    options: [
      'Porque tecidos e oclusão precisam se adaptar e os dentes permanecem sujeitos à recidiva e a mudanças ao longo da vida.',
      'Apenas para melhorar a cor dos dentes.',
      'Porque todo movimento ortodôntico desaparece em 24 horas sem contenção.',
      'Somente para pacientes que usaram aparelho removível.',
    ],
    answer: 0,
    explanation: 'O protocolo e a duração são individualizados; retenção prolongada ou permanente pode ser indicada para manter o resultado.',
  },
  {
    id: 'orto-05',
    kind: 'boolean',
    difficulty: 2,
    prompt: 'Avalie a influência do crescimento facial.',
    statement: 'Idade, estágio de maturação e padrão de crescimento podem modificar objetivos, oportunidade e resposta ao tratamento ortodôntico.',
    answer: true,
    explanation: 'Pacientes não apresentam o mesmo potencial nem a mesma direção de crescimento; o planejamento deve integrar maturação esquelética e padrão facial.',
  },
  {
    id: 'orto-06',
    kind: 'multi',
    difficulty: 2,
    prompt: 'Quais medidas ajudam a controlar o biofilme durante o tratamento ortodôntico fixo?',
    options: [
      'Higienizar cuidadosamente ao redor de brackets, fios e margem gengival.',
      'Usar recursos interproximais indicados e dentifrício fluoretado.',
      'Manter acompanhamento e prevenção individualizados conforme o risco.',
      'Delegar toda a higiene ao ortodontista nas consultas.',
    ],
    answers: [0, 1, 2],
    explanation: 'Aparelhos fixos aumentam nichos de retenção. Autocuidado, orientação profissional e controle de risco reduzem gengivite e lesões de mancha branca.',
  },
  {
    id: 'orto-07',
    kind: 'blank',
    difficulty: 2,
    prompt: 'Complete a frase',
    sentence: 'O movimento no qual coroa e raiz se deslocam na mesma direção e em magnitude semelhante é denominado ___.',
    answer: 'translação',
    bank: ['translação', 'inclinação', 'rotação', 'extrusão'],
    explanation: 'Na translação, também chamada movimento de corpo, coroa e raiz avançam de modo semelhante. Ela exige um sistema de forças diferente daquele usado para inclinação simples.',
  },
  {
    id: 'orto-08',
    kind: 'order',
    difficulty: 2,
    prompt: 'Ordene as fases gerais de um tratamento ortodôntico',
    steps: [
      'Obter anamnese, exame e registros diagnósticos indicados',
      'Definir diagnóstico, objetivos e plano com consentimento informado',
      'Controlar doenças bucais ativas antes da movimentação',
      'Instalar o aparelho e realizar a fase ativa com monitoramento',
      'Finalizar o posicionamento dentário e remover o aparelho ativo',
      'Instalar a contenção e acompanhar estabilidade e saúde bucal',
    ],
    explanation: 'A movimentação deve começar com condições bucais controladas e objetivos definidos. Após a fase ativa, contenção e acompanhamento são necessários porque os tecidos se reorganizam e mudanças continuam ao longo da vida.',
  },
  {
    id: 'orto-09',
    kind: 'match',
    difficulty: 2,
    prompt: 'Relacione o movimento ortodôntico com sua descrição',
    pairs: [
      { left: 'Intrusão', right: 'Deslocamento do dente em direção apical' },
      { left: 'Extrusão', right: 'Deslocamento do dente para fora do alvéolo' },
      { left: 'Rotação', right: 'Giro do dente ao redor de seu eixo longitudinal' },
      { left: 'Torque radicular', right: 'Movimento predominante da raiz no sentido vestibulolingual' },
    ],
    explanation: 'Cada movimento requer um sistema de forças e controle de ancoragem próprios. Magnitude, direção e duração inadequadas aumentam efeitos indesejados e risco biológico.',
  },
];
