import type { ExerciseSeed } from '../types';

export const PAT_EXERCISES: ExerciseSeed[] = [
  {
    id: 'pat-01',
    kind: 'choice',
    difficulty: 2,
    prompt: 'Qual é a interpretação correta de uma placa branca oral que não se desprende à raspagem?',
    options: [
      'Ela requer descrição clínica e diagnóstico diferencial; a ausência de raspagem não define sozinha a causa.',
      'Ela confirma candidíase pseudomembranosa.',
      'Ela é sempre uma variação normal sem necessidade de acompanhamento.',
      'Ela confirma malignidade e dispensa biópsia.',
    ],
    answer: 0,
    explanation: 'Lesões brancas não removíveis incluem alterações reacionais, imunomediadas e potencialmente malignas. História, localização, aspecto e persistência orientam investigação.',
  },
  {
    id: 'pat-02',
    kind: 'boolean',
    difficulty: 2,
    prompt: 'Avalie a conduta diante de uma úlcera oral.',
    statement: 'Uma úlcera indolor pode ser observada indefinidamente, mesmo sem causa evidente e sem cicatrização.',
    answer: false,
    explanation: 'Úlcera inexplicada, suspeita ou que não cicatriza após remoção de possível trauma em cerca de 2–3 semanas deve ser encaminhada para investigação e possível biópsia.',
  },
  {
    id: 'pat-03',
    kind: 'multi',
    difficulty: 2,
    prompt: 'Quais grupos de doenças podem produzir aumento de volume na região oral ou maxilofacial?',
    options: [
      'Processos inflamatórios ou infecciosos.',
      'Cistos e outras lesões odontogênicas.',
      'Neoplasias benignas ou malignas.',
      'Somente variações anatômicas normais.',
    ],
    answers: [0, 1, 2],
    explanation: 'Aumento de volume é um sinal, não um diagnóstico. Duração, consistência, limites, sintomas, imagem e, quando indicada, análise histopatológica definem a investigação.',
  },
  {
    id: 'pat-04',
    kind: 'choice',
    difficulty: 2,
    prompt: 'Quais características devem ser registradas ao examinar linfonodos cervicais?',
    options: [
      'Localização, tamanho, consistência, mobilidade ou fixação e sensibilidade.',
      'Somente presença ou ausência de dor.',
      'Apenas a cor da pele sobrejacente.',
      'Somente o número de dentes cariados.',
    ],
    answer: 0,
    explanation: 'A caracterização sistemática dos linfonodos integra o exame de cabeça e pescoço e ajuda a direcionar o diagnóstico e o encaminhamento.',
  },
  {
    id: 'pat-05',
    kind: 'boolean',
    difficulty: 1,
    prompt: 'Avalie o exame facial.',
    statement: 'A comparação bilateral pode revelar assimetria causada por aumento de volume ou alteração estrutural e o achado deve ser registrado.',
    answer: true,
    explanation: 'Alguma assimetria fisiológica é comum, mas uma diferença nova ou pronunciada pode ser clinicamente relevante e deve ser contextualizada.',
  },
  {
    id: 'pat-06',
    kind: 'multi',
    difficulty: 3,
    prompt: 'Quais achados em uma lesão pigmentada oral aumentam a necessidade de avaliação especializada?',
    options: [
      'Lesão nova ou sem diagnóstico clínico seguro.',
      'Assimetria, limites irregulares ou variação de cor.',
      'Crescimento, ulceração ou sangramento.',
      'Ausência de mudança percebida pelo paciente, que exclui malignidade.',
    ],
    answers: [0, 1, 2],
    explanation: 'Localização, distribuição, cor, tamanho, limites, superfície e evolução devem ser documentados. Estabilidade relatada isoladamente não exclui doença relevante nem eventual biópsia.',
  },
  {
    id: 'pat-07',
    kind: 'blank',
    difficulty: 1,
    prompt: 'Complete a frase',
    sentence: 'A remoção de tecido vivo para análise histopatológica é denominada ___.',
    answer: 'biópsia',
    bank: ['biópsia', 'citologia', 'diascopia', 'aspiração'],
    explanation: 'A biópsia fornece tecido para avaliação microscópica e pode ser incisional ou excisional, conforme tamanho, localização, hipótese diagnóstica e planejamento do caso.',
  },
  {
    id: 'pat-08',
    kind: 'order',
    difficulty: 3,
    prompt: 'Ordene a avaliação de uma úlcera compatível com trauma e sem sinais clínicos de alarme',
    steps: [
      'Investigar início, duração, sintomas e possível agente traumático',
      'Examinar, palpar, medir e documentar a lesão e os linfonodos regionais',
      'Eliminar o possível agente traumático quando isso puder ser feito com segurança',
      'Reavaliar a cicatrização em cerca de duas semanas',
      'Encaminhar para investigação e possível biópsia se a lesão persistir',
    ],
    explanation: 'Uma causa traumática plausível permite reavaliação curta após sua remoção. Lesão suspeita, progressiva ou sem causa evidente não deve aguardar esse prazo e requer encaminhamento imediato.',
  },
  {
    id: 'pat-09',
    kind: 'match',
    difficulty: 2,
    prompt: 'Relacione a lesão fundamental com sua descrição',
    pairs: [
      { left: 'Mácula', right: 'Alteração plana e circunscrita de cor' },
      { left: 'Pápula', right: 'Pequena elevação sólida e circunscrita' },
      { left: 'Vesícula', right: 'Pequena elevação preenchida por líquido' },
      { left: 'Úlcera', right: 'Perda do epitélio com exposição do tecido conjuntivo' },
    ],
    explanation: 'Descrever a lesão fundamental, superfície, cor, limites, consistência e distribuição ajuda a organizar o diagnóstico diferencial, mas não substitui a investigação etiológica.',
  },
];
