import type { ExerciseSeed } from '../types';

export const URG_EXERCISES: ExerciseSeed[] = [
  {
    id: 'urg-01',
    kind: 'boolean',
    difficulty: 2,
    prompt: 'Avalie a conduta inicial diante de provável síncope.',
    statement: 'Deve-se interromper o atendimento, colocar o paciente em decúbito dorsal com pernas elevadas quando não houver contraindicação, avaliar ABC e monitorar sinais vitais.',
    answer: true,
    explanation: 'Palidez, sudorese e perda breve de consciência são compatíveis com síncope. Recuperação ausente ou atípica exige considerar outras causas e acionar emergência.',
  },
  {
    id: 'urg-02',
    kind: 'choice',
    difficulty: 3,
    prompt: 'Um paciente apresenta início súbito de dispneia, sibilância, urticária e hipotensão após receber um medicamento. Qual é a conduta prioritária?',
    options: [
      'Acionar emergência e administrar imediatamente adrenalina 1 mg/mL por via intramuscular na face anterolateral da coxa.',
      'Administrar apenas anti-histamínico oral e aguardar.',
      'Manter o procedimento odontológico até confirmar a causa.',
      'Aplicar adrenalina intravenosa em bolus como primeira medida de rotina.',
    ],
    answer: 0,
    explanation: 'Na anafilaxia, adrenalina IM é primeira linha: 0,01 mg/kg, máximo de 0,5 mg por dose, repetível em 5–15 minutos conforme resposta e protocolo. Anti-histamínicos não a substituem.',
  },
  {
    id: 'urg-03',
    kind: 'multi',
    difficulty: 3,
    prompt: 'Selecione as condutas corretas diante de suspeita de hipoglicemia.',
    options: [
      'Se o paciente estiver consciente e puder deglutir, oferecer 15–20 g de carboidrato de absorção rápida.',
      'Reavaliar clinicamente e, quando disponível, verificar novamente a glicemia após cerca de 15 minutos.',
      'Dar líquido açucarado por via oral mesmo ao paciente inconsciente.',
      'Se não puder deglutir, acionar emergência e usar glucagon ou glicose intravenosa apenas conforme treinamento e protocolo.',
    ],
    answers: [0, 1, 3],
    explanation: 'Sudorese, tremor e alteração comportamental são possíveis sinais. Nada deve ser oferecido por via oral quando a deglutição não é segura.',
  },
  {
    id: 'urg-04',
    kind: 'choice',
    difficulty: 3,
    prompt: 'Durante o atendimento, um paciente desenvolve dor torácica nova, opressiva e acompanhada de sudorese. Qual é a melhor resposta inicial?',
    options: [
      'Interromper o atendimento, avaliar ABC e sinais vitais e acionar precocemente o serviço de emergência.',
      'Concluir o procedimento antes de avaliar a dor.',
      'Presumir origem odontogênica se o paciente também tiver dor dentária.',
      'Administrar nitrato sem verificar indicação ou contraindicações.',
    ],
    answer: 0,
    explanation: 'O quadro pode representar síndrome coronariana aguda. Aspirina mastigável e nitrato só cabem conforme protocolo, indicação e contraindicações; não se deve atrasar o acionamento.',
  },
  {
    id: 'urg-05',
    kind: 'boolean',
    difficulty: 2,
    prompt: 'Avalie a conduta durante uma convulsão.',
    statement: 'É recomendado forçar a abertura da boca e colocar um objeto entre os dentes para impedir que o paciente engula a língua.',
    answer: false,
    explanation: 'Afaste objetos, proteja a cabeça, não restrinja movimentos, não coloque nada na boca e cronometre a crise. Após a crise, avalie ABC e posicione lateralmente quando apropriado.',
  },
  {
    id: 'urg-06',
    kind: 'multi',
    difficulty: 3,
    prompt: 'Em quais situações relacionadas a uma convulsão o serviço de emergência deve ser acionado?',
    options: [
      'Crise com duração de 5 minutos ou mais.',
      'Crises repetidas sem recuperação da consciência.',
      'Primeira crise, gestação, trauma importante ou dificuldade respiratória.',
      'Toda contração muscular breve em paciente plenamente consciente, sem avaliação adicional.',
    ],
    answers: [0, 1, 2],
    explanation: 'Reconhecimento, proteção e acionamento oportuno são essenciais. O contexto e a recuperação do paciente determinam a necessidade de suporte avançado.',
  },
  {
    id: 'urg-07',
    kind: 'blank',
    difficulty: 2,
    prompt: 'Complete a recomendação para adultos',
    sentence: 'Na ressuscitação cardiopulmonar de um adulto, a frequência recomendada de compressões torácicas é de ___ por minuto.',
    answer: '100 a 120',
    bank: ['100 a 120', '40 a 60', '60 a 80', '140 a 160'],
    explanation: 'Compressões de alta qualidade em adultos são realizadas a 100–120 por minuto, com profundidade de 5–6 cm, retorno completo do tórax e interrupções mínimas.',
  },
  {
    id: 'urg-08',
    kind: 'order',
    difficulty: 3,
    prompt: 'Ordene o suporte básico de vida diante de um adulto que colapsou',
    steps: [
      'Confirmar a segurança da cena e verificar a responsividade',
      'Pedir ajuda, acionar o serviço de emergência e solicitar um DEA',
      'Avaliar simultaneamente respiração e pulso por no máximo 10 segundos',
      'Iniciar compressões torácicas se não houver respiração normal e pulso definido',
      'Ligar o DEA assim que disponível e seguir suas instruções',
    ],
    explanation: 'O reconhecimento rápido, o acionamento do sistema de emergência, a RCP de qualidade e a desfibrilação precoce formam a cadeia de sobrevivência. Gasping não é respiração normal.',
  },
  {
    id: 'urg-09',
    kind: 'match',
    difficulty: 2,
    prompt: 'Relacione a emergência com a intervenção inicial característica',
    pairs: [
      { left: 'Síncope provável', right: 'Decúbito dorsal e elevação das pernas quando não houver contraindicação' },
      { left: 'Anafilaxia', right: 'Adrenalina intramuscular imediata na face anterolateral da coxa' },
      { left: 'Hipoglicemia com deglutição segura', right: 'Carboidrato oral de absorção rápida' },
      { left: 'Parada cardiorrespiratória', right: 'RCP de alta qualidade e uso precoce do DEA' },
    ],
    explanation: 'Em todas as situações, deve-se interromper o atendimento, avaliar ABC, monitorar e acionar ajuda conforme a gravidade. A intervenção específica não substitui o suporte geral.',
  },
];
